name: Test
on:
  workflow_dispatch:
    inputs:
      file_name:
        description: File name
        required: true
        default: Firefox Setup 100.0.exe

jobs:
  Download-Uncompress:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing
        run: |
         cd $HOME
         mkdir Download
         mkdir Files
         pwd
