name: Hash file 
on:
  workflow_dispatch:
    inputs:
      file_name:
        description: File name
        required: true
        default: Example.exe
      file_link:
        description: File Link
        required: true
        default: https://example.org/Example.exe

jobs:
  Hashing:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing
        run: |
         
